package message

type Headers interface {
	GetBornHost() (string, error)
	GetBornTimestamp() (int64, error)
	GetCompression() (int16, error)
	GetCorrelationId() (string, error)
	GetDelayTime() (int64, error)
	GetDeliveryCount() (int, error)
	GetDestination() (string, error)
	GetDurability() (int16, error)
	GetExpireTime() (int64, error)
	GetMessageId() (string, error)
	GetMessageKey() (string, error)
	GetPriority() (int16, error)
	GetStoreHost() (string, error)
	GetStoreTimestamp() (int64, error)
	GetTraceId() (string, error)
	GetTransactionId() (string, error)
	SetBornHost(bornHost string) (Headers, error)
	SetBornTimestamp(bornTimestamp int64) (Headers, error)
	SetCompression(compression int16) (Headers, error)
	SetCorrelationId(scorrelationId string) (Headers, error)
	SetDelayTime(delayTime int64) (Headers, error)
	SetDeliveryCount(deliveryCount int) (Headers, error)
	SetDestination(destination string) (Headers, error)
	SetDurability(durability int16) (Headers, error)
	SetExpireTime(expireTime int64) (Headers, error)
	SetMessageId(messageId string) (Headers, error)
	SetMessageKey(messageKey string) (Headers, error)
	SetPriority(priority int16) (Headers, error)
	SetStoreHost(storeHost string) (Headers, error)
	SetStoreTimestamp(storeTimestamp int64) (Headers, error)
	SetTraceId(traceId string) (Headers, error)
	SetTransactionId(transactionId string) (Headers, error)
}
